---
- name: Testing andrewrothstein.dragonfly2
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'dfget version'
      ansible.builtin.command: /usr/local/bin/dfget version
      changed_when: false
      register: dfget_test_output
    - name: Output from 'dfget version'
      ansible.builtin.debug:
        msg: '{{ dfget_test_output.stdout }}'
