---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/dfget version
    register: dfget_test_output
  - name: dfget version
    debug:
      msg: '{{ dfget_test_output.stdout }}'
