---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install in {{ dragonfly2_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ dragonfly2_install_dir }}'
  register: dragonfly2_binary
  changed_when: false
- name: Downloading and installing dragonfly2
  when: not dragonfly2_binary.stat.exists
  block:
    - name: Download {{ dragonfly2_url }} to {{ dragonfly2_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ dragonfly2_url }}'
        dest: '{{ dragonfly2_tmp_archive }}'
        mode: '644'
        checksum: '{{ dragonfly2_checksum }}'
    - name: Mkdir {{ dragonfly2_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ dragonfly2_install_dir }}'
        state: directory
        mode: '755'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchive {{ dragonfly2_tmp_archive }} to {{ dragonfly2_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ dragonfly2_tmp_archive }}'
        dest: '{{ dragonfly2_install_dir }}'
        creates: '{{ dragonfly2_install_dir }}/dfget'
  always:
    - name: Rm {{ dragonfly2_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ dragonfly2_tmp_archive }}'
        state: absent
- name: Linking apps
  become: true
  become_user: root
  with_items: '{{ dragonfly2_apps }}'
  ansible.builtin.file:
    src: '{{ dragonfly2_install_dir }}/{{ item }}'
    dest: '{{ dragonfly2_parent_install_dir }}/bin/{{ item }}'
    state: link
